services:
  - type: web
    name: vehixai
    runtime: python
    plan: free

    buildCommand: pip install --no-cache-dir -r requirements.txt --extra-index-url https://download.pytorch.org/whl/cpu

    startCommand: streamlit run dashboard/app.py --server.address 0.0.0.0 --server.port $PORT

    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
